version: "3"

services:
  server-a-api:
    build: ./server-a-api
    ports:
      - 3000:3000
    env_file:
        - ./server-a-api/.env
        
  server-b-api:
    build: ./server-a-api
    ports:
      - 3001:3001
    env_file:
        - ./server-a-api/.env